name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  golang-build:
    runs-on: ubuntu-latest
    environment:
      - IMAGE_NAME: ghcr.io/spolab/golang-build:$(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file golang-build/Dockerfile --tag $(IMAGE_NAME) .
    - name: Push the Docker image
      run: docker push $(IMAGE_NAME)
