name: Build the images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOLANG_BUILD_IMAGE: ghcr.io/spolab/golang-builder:v0.0.1
  GOLANG_RUNTIME_IMAGE: ghcr.io/spolab/golang-runtime:v0.0.1

jobs:
  golang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file golang-build/Dockerfile --tag $GOLANG_BUILD_IMAGE .
    - name: Login to the container repository
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: spolab
        password: ${{ secrets.PAT }}
    - name: Push the Docker image
      run: docker push $GOLANG_BUILD_IMAGE

  golang-runtime:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file golang-runtime/Dockerfile --tag $GOLANG_RUNTIME_IMAGE .
    - name: Login to the container repository
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: spolab
        password: ${{ secrets.PAT }}
    - name: Push the Docker image
      run: docker push $GOLANG_RUNTIME_IMAGE
