name: Build the images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  golang-build-image: gchr.io/spolab/golab-builder:$(date +%s)

jobs:
  golang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file golang-build/Dockerfile --tag ${{golang-build-image}} .
    - name: Push the Docker image
      run: docker push ${{golang-build-image}}
