name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  golang-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file golang-build/Dockerfile --tag spolab/golang-build:$(date +%s) .
    - name: Push the Docker image
      run: docker push spolab/golang-build:$(date +%s)
